ADM-413 feat: update cloudformation.yml to install trivy.

diff --git a/.buildkite/ops/build b/.buildkite/ops/build
--- a/.buildkite/ops/build
+++ b/.buildkite/ops/build
@@ -12,21 +12,22 @@ display_help() {
 }
 
 build_backend() {
-    # aws configure set region $AWS_REGION
-    # eval $(aws sts assume-role --role-arn $AWS_GITHUB_ACTION_ROLE --role-session-name buildkite | jq -r '.Credentials | to_entries | map(.key + "=" + "\"" + (.value | tostring) + "\"") | .[]')
-    # aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-    # echo "start to build backend 11"
-    # docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest ./ -f ./infra/Dockerfile.backend
-    # echo "start to build backend 22"
-    # docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER} ./ -f ./infra/Dockerfile.backend
-    # docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
-    # docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
-    # docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
-    # docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
-    export PATH="$PATH:~/bin/trivy"
-    echo "trivy version"
-    trivy --version
-    ~/bin/trivy image --severity HIGH,CRITICAL --exit-code 1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
+    aws configure set region $AWS_REGION
+    eval $(aws sts assume-role --role-arn $AWS_GITHUB_ACTION_ROLE --role-session-name buildkite | jq -r '.Credentials | to_entries | map(.key + "=" + "\"" + (.value | tostring) + "\"") | .[]')
+    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
+    set +e
+    docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest ./ -f ./infra/Dockerfile.backend
+    docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER} ./ -f ./infra/Dockerfile.backend
+    trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed --format table --ignorefile .trivyignore $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
+    if [[ $? -ne 0 ]]; then
+        echo "Trivy scan failed"
+    else
+        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
+        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
+    fi
+    set -e
+    docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:latest
+    docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/heartbeat_backend:hb${BUILDKITE_BUILD_NUMBER}
 }
 
 build_mockserver() {
