[frontend]Let github action wait for buildkite

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -398,6 +398,7 @@ jobs:
       #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
   deploy-e2e:
+    if: ${{ "!contains(github.event.head_commit.message, 'frontend')" || "!contains(github.event.head_commit.message, 'backend')" }}
     runs-on: ubuntu-latest
     needs:
       - build-backend
@@ -405,7 +406,31 @@ jobs:
     steps:
       - name: Checkout repo
         # uses: actions/checkout@v4
-        run: echo "This is an empty step"
+#        run: echo "This is an empty step"
+        run: |
+          max_attempts=20
+          attempt_count=0
+
+          while [ $attempt_count -lt $max_attempts ]; do
+            ((attempt_count++))
+            value=$(curl -H "Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}" -X GET "https://api.buildkite.com/v2/organizations/heartbeat-backup/pipelines/heartbeat/builds?branch=main&commit=${{ GITHUB_SHA }}&state=passed" | jq '.[0].jobs[] | select(.name == ":rocket: Deploy e2e" and .state == "passed") | any')
+
+            echo $GITHUB_SHA
+            echo $value
+            if [ "$value" == "true" ]; then
+              echo "Successfully deploy to E2E"
+              break
+            else
+              echo "WIP..."
+              sleep 60
+            fi
+          done
+
+          if [ $attempt_count -eq $max_attempts ]; then
+            echo "Failed to wait for E2E deployment with Maximum attempts reached. Exiting..."
+            exit 1
+          fi
+
       # - name: Update docker-compose.yaml
       #   run: |
       #     sed -i -e 's/heartbeat_backend:latest/${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_HOST }}\/heartbeat_backend:hb${{ github.run_number }}/g' ops/infra/docker-compose.yml
