pref(px): add px check

diff --git a/.github/workflows/BuildAndDeploy.yml b/.github/workflows/BuildAndDeploy.yml
--- a/.github/workflows/BuildAndDeploy.yml
+++ b/.github/workflows/BuildAndDeploy.yml
@@ -124,6 +124,26 @@ jobs:
           name: backend-license-report
           path: backend/build/reports/dependency-license/
           retention-days: ${{ vars.RETENTION_DAYS }}
+  px-check:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./frontend
+    steps:
+      - uses: actions/checkout@v4
+      - name: CSS unit `px` check
+        run: |
+          result=$(grep -rin --exclude='*.svg' --exclude='*.png'  --exclude='*.yaml'  --exclude-dir='node_modules' "[0-9]\+px" ./frontend)
+
+          file_count=$(echo "$result" | wc -l)
+
+          if [ $file_count -gt 0 ]; then
+            echo "Error: Found files with [0-9]+px pattern:"
+            echo "$result"
+            exit 1
+          else
+            echo "No matching files found."
+          fi
   frontend-check:
     runs-on: ubuntu-latest
     defaults:
@@ -188,6 +208,7 @@ jobs:
     needs:
       - fossa-check
       - frontend-check
+      - px-check
       - backend-check
       - security-check
       - shellcheck
